data = {
    "en": {
        "no_permission": "You do not have permission to use this command!",
        "not_command_sender": "You are not the sender of that command!",
        "vote_message": "Thank you for voting for Doge Utilities!",
        "banned_message": "You are banned from using Doge Utilities!",
        "error_message": "Oops! Doge Utilities has ran into an error...",
        "use_in_server": "Please use Doge Utilities in a server for the best experience!",
        "no_reminders": "You have no active reminders",
        "reminders": "Reminders",
        "reminder": "Reminder",
        "time": "Time",
        "text": "Text",
        "vote_again": "Don't forget to vote for me!",
        "todo_list": "To-do List",
        "todo_empty": "Your to-do list is empty",
        "generate_number": "Generate Number",
        "number_prompt": "Your random number is",
        "cpu_usage": "CPU Usage",
        "ram_usage": "RAM Usage",
        "thread_count": "Thread Count",
        "joined_guilds": "Joined Guilds",
        "active_shards": "Active Shards",
        "member_count": "Member Count",
        "channel_count": "Channel Count",
        "command_count": "Command Count",
        "disnake_version": "Disnake Version",
        "bot_version": "Bot Version",
        "bot_uptime": "Bot Uptime",
        "latency": "Latency",
        "shard": "Shard",
        "members_lower": "members",
        "guilds_lower": "guilds",
        "i_choose": "I choose",
        "shard_count": "Shard Count",
        "current_shard": "Current Shard",
        "reminder_removed": "That reminder has been successfully removed",
        "reminder_added": "You will be reminded in **{}**",
        "minute": "minute",
        "minutes": "minutes",
        "support_server": "Doge Utilities support server",
        "user_accounts": "User accounts",
        "bot_accounts": "Bot accounts",
        "total_members": "Total members",
        "guild_members": "Guild Members",
        "todo_added": 'Successfully added **"{}"** to your to-do list',
        "todo_removed": 'Successfully removed **"{}"** from your to-do list',
        "uptime_description": "Doge Utilities has been running for",
        "current_time": "Time",
        "current_date": "Date",
        "weekday": "Weekday",
        "time_description": "Information for",
        "weekdays": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "vote_websites": "You can vote for me on these websites",
        "vote_reminder_added": "A **12 hour reminder** has been successfully added!",
        "vote_reminder_exists": "A reminder already exists!",
        "vote_add_reminder": "Add a reminder",
    },
    "zh-cn": {
        "no_permission": "你没有权限用这个指令!",
        "not_command_sender": "这个指令不是你发的!",
        "vote_message": "谢谢你给我投票!",
        "banned_message": "你已被禁止使用Doge Utilities!",
        "error_message": "很抱歉，Doge Utilities出错了。。。",
        "use_in_server": "请你在服务器里用Doge Utilities!",
        "no_reminders": "你没有提醒",
        "reminders": "提醒",
        "reminder": "提醒",
        "time": "时间",
        "text": "文字",
        "vote_again": "不要忘记给我投票!",
        "todo_list": "待办事项列表",
        "todo_empty": "你的待办事列表是空的",
        "generate_number": "生成数字",
        "number_prompt": "你的随机数字是",
        "cpu_usage": "CPU使用率",
        "ram_usage": "RAM使用率",
        "thread_count": "机器人程序数",
        "joined_guilds": "机器人服务器",
        "active_shards": "机器人碎片",
        "member_count": "用户数",
        "channel_count": "频道数",
        "command_count": "指令数",
        "disnake_version": "Disnake版本",
        "bot_version": "机器人版本",
        "bot_uptime": "机器人运行时间",
        "latency": "延迟",
        "shard": "碎片",
        "members_lower": "用户",
        "guilds_lower": "服务器",
        "i_choose": "我选择",
        "shard_count": "碎片数",
        "current_shard": "当前碎片",
        "reminder_removed": "那个提醒已被成功移除",
        "reminder_added": "你会在**{}**后被提醒",
        "minute": "分钟",
        "minutes": "分钟",
        "support_server": "我的服务器",
        "user_accounts": "用户账号",
        "bot_accounts": "机器人账号",
        "total_members": "全部账号",
        "guild_members": "服务器成员",
        "todo_added": '我成功的把 **"{}"** 加到了你的待办事列表',
        "todo_removed": '我成功的把你待办事列表里的 **"{}"** 移除了',
        "uptime_description": "我已经运行了",
        "current_time": "时间",
        "current_date": "日期",
        "weekday": "星期",
        "time_description": "关于",
        "weekdays": ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期天"],
        "vote_websites": "你可以在这些网站上给我投票",
        "vote_reminder_added": "我成功的给你加了一个**12小时的提醒**!",
        "vote_reminder_exists": "你已经有了一个提醒!",
        "vote_add_reminder": "加一个提醒",
    },
    "de": {
        "no_permission": "Du hast keine Berechtigung diesen Befehl zu benutzen!",
        "not_command_sender": "Du hast den Befehl nicht benutzt!",
        "vote_message": "Danke dass du Doge Utilities Bewertet hast!",
        "banned_message": "Du bist von Doge Utilities gesperrt",
        "error_message": "Ups! Doge Utilities hatte einen Fehler...",
        "shard": "Shard",
        "latency": "Latenz",
        "time": "Wann",
        "text": "Text",
        "reminder": "Erinnerung",
        "reminders": "Erinnerungen",
        "cpu_usage": "CPU Auslastung",
        "ram_usage": "RAM Auslastung",
        "thread_count": "Anzahl der Threads",
        "joined_guilds": "Servern beigetreten",
        "active_shards": "Aktive Shards",
        "member_count": "Anzahl der Mitglieder",
        "channel_count": "Anzahl der Kanäle",
        "command_count": "Anzahl der Commands",
        "disnake_version": "Disnake Version",
        "bot_version": "Bot Version",
        "bot_uptime": "Bot online seit",
        "i_choose": "Ich wähle",
        "members_lower": "Mitglieder",
        "guilds_lower": "Server",
        "current_shard": "Aktueller Shard",
        "shard_count": "Shards",
        "use_in_server": "Bitte nutze Doge Utilities in einem Server für das bestmögliche Ergebnis!",
        "no_reminders": "Du hast keine aktiven Erinnerungen",
        "vote_again": "Vergiss nicht für mich zu voten!",
        "todo_list": "To-do Liste",
        "todo_empty": "Deine To-do Liste ist leer",
        "generate_number": "Generiere eine Nummer",
        "number_prompt": "Deine generierte Nummer ist",
        "reminder_removed": "Diese Erinnerung wurde erfolgreich entfernt",
        "reminder_added": "Du wirst erinnert in **{}**",
        "minute": "Minute",
        "minutes": "Minuten",
        "support_server": "Doge Utilities Support Server",
        "user_accounts": "Nutzer Accounts",
        "bot_accounts": "Bot Accounts",
        "total_members": "Alle Mitglieder",
        "guild_members": "Server Mitglieder",
        "todo_added": '**"{}"** wurde erfolgreich zur To-do Liste hinzugefügt',
        "todo_removed": '**"{}"** wurde erfolgreich aus der To-do Liste entfernt',
        "uptime_description": "Doge Utilities ist online seit",
        "current_time": "Uhrzeit",
        "current_date": "Datum",
        "weekday": "Wochentag",
        "time_description": "Informationen für",
        "weekdays": ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
        "vote_websites": "Du kannst für mich auf folgenden Websites voten",
        "vote_reminder_added": "Eine **12 Stunden Erinnerung** wurde erfolgreich hinzugefügt!",
        "vote_reminder_exists": "Es gibt bereits eine Erinnerung!",
        "vote_add_reminder": "Füge eine Erinnerung hinzu",
    },
    "ru": {
        "no_permission": "У вас нет разрешений на использование этой команды!",
        "not_command_sender": "Вы не являетесь отправителем данной команды!",
        "vote_message": "Спасибо за то, что вы проголосовали за меня!",
        "banned_message": "Вам запретили использовать Doge Utilities!",
        "error_message": "Упс... Doge Utilities столкнулся с ошибкой...",
        "use_in_server": "Пожалуйста, используйте Doge Utilities на сервере для лучшего опыта!",
        "no_reminders": "У вас нет активных напоминаний",
        "reminders": "Напоминания",
        "time": "Время",
        "text": "Текст",
        "todo_list": "Список дел",
        "support_server": "Сервер поддержки Doge Utilities",
        "vote_again": "Не забывай голосовать за меня!",
        "todo_empty": "Ваш список дел пустой",
        "generate_number": "Сгенерировать число",
        "number_prompt": "Ваше случайное число",
        "cpu_usage": "Использование CPU",
        "ram_usage": "Использование RAM",
        "thread_count": "Количество треадов",
        "active_shards": "Активные шарды",
        "member_count": "Количество участников",
        "channel_count": "Количество каналов",
        "command_count": "Количество команд",
        "disnake_version": "Версия Disnake",
        "bot_version": "Версия бота",
        "bot_uptime": "Время работы",
        "shard": "Шард",
        "members_lower": "участники",
        "guilds_lower": "гильдии",
        "i_choose": "Я выбрал",
        "shard_count": "Количество шардов",
        "current_shard": "Текущий шард",
        "reminder_removed": "Это напоминание было успешно удалено",
        "reminder_added": "Вам напомнят в **{}**",
        "minute": "минута",
        "minutes": "минуты",
        "latency": "Задержка",
        "joined_guilds": "Гильдий",
        "uptime_description": "Doge Utilities работает",
    },
}
data["zh-tw"] = data["zh-cn"]

def get(language, key):
    language = language.lower()
    key = key.lower()
    if language not in data.keys():
        language = "en"
    language_data = data[language]
    if key not in language_data:
        language_data = data["en"]
        if key not in language_data:
            return "?"
        else:
            return language_data[key]
    else:
        return language_data[key]

