data = {
    "en": {
        "no_permission": "You do not have permission to use this command!",
        "not_command_sender": "You are not the sender of that command!",
        "vote_message": "Thank you for voting for Doge Utilities!",
        "banned_message": "You are banned from using Doge Utilities!",
        "error_message": "Oops! Doge Utilities has ran into an error...",
        "use_in_server": "Please use Doge Utilities in a server for the best experience!",
        "no_reminders": "You have no active reminders",
        "reminders": "Reminders",
        "reminder": "Reminder",
        "time": "Time",
        "text": "Text",
        "vote_again": "Don't forget to vote for me!",
        "todo_list": "To-do List",
        "todo_empty": "Your to-do list is empty",
        "generate_number": "Generate Number",
        "number_prompt": "Your random number is",
        "cpu_usage": "CPU Usage",
        "ram_usage": "RAM Usage",
        "thread_count": "Thread Count",
        "joined_guilds": "Joined Guilds",
        "active_shards": "Active Shards",
        "member_count": "Member Count",
        "channel_count": "Channel Count",
        "command_count": "Command Count",
        "disnake_version": "Disnake Version",
        "bot_version": "Bot Version",
        "git_commit_hash_upper": "Git Commit Hash",
        "last_updated_upper": "Last Updated",
        "bot_uptime": "Bot Uptime",
        "latency": "Latency",
        "shard": "Shard",
        "members_lower": "members",
        "guilds_lower": "guilds",
        "i_choose": "I choose",
        "shard_count": "Shard Count",
        "current_shard": "Current Shard",
        "reminder_removed": "That reminder has been successfully removed!",
        "reminder_added": "You will be reminded in **{}**",
        "support_server": "Doge Utilities support server",
        "user_accounts": "User accounts",
        "bot_accounts": "Bot accounts",
        "total_members": "Total members",
        "guild_members": "Guild Members",
        "todo_added": 'Successfully added **"{}"** to your to-do list',
        "todo_removed": 'Successfully removed **"{}"** from your to-do list',
        "uptime_description": "Doge Utilities has been running for",
        "current_time": "Time",
        "current_date": "Date",
        "weekday": "Weekday",
        "time_description": "Information for",
        "weekdays": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        "vote_websites": "You can vote for me on these websites",
        "vote_reminder_added": "A **12 hour reminder** has been successfully added!",
        "vote_reminder_exists": "A reminder already exists!",
        "vote_add_reminder": "Add a reminder",
        "vote_messages_enabled": "Vote messages have been successfully **enabled**",
        "vote_messages_disabled": "Vote messages have been successfully **disabled**",
        "enabled_lower": "enabled",
        "disabled_lower": "disabled",
        "vote_messages_status": "Vote messages are currently **{}**",
        "language_update": "Your preferred language has been set to **{}**",
        "language_name": "English",
        "website_links": "Here are the links to my website",
        "website": "Website",
        "dashboard": "Dashboard",
        "user_kicked": "**{}** has been **successfully kicked**",
        "user_banned": "**{}** has been **successfully banned**",
        "unable_to_kick": "Unable to kick **{}**",
        "unable_to_ban": "Unable to ban **{}**",
        "mention_valid_user": "Please mention a valid user!",
        "user_id": "User ID",
        "user_tag": "Tag",
        "creation_time": "Creation Time",
        "public_flags": "Public Flags",
        "bot_user": "Bot User",
        "system_user": "System User",
        "command_cooldown": "Command Cooldown",
        "command_cooldown_description": "Please wait **{}** before using the `{}` command again",
        "invalid_duration": "Please enter a valid duration!",
        "no_permission_kick": "You do not have permission to kick **{}**!",
        "no_permission_ban": "You do not have permission to ban **{}**!",
        "unable_to_mute": "Unable to mute **{}**",
        "no_permission_mute": "You do not have permission to mute **{}**!",
        "no_permission_unmute": "You do not have permission to unmute **{}**!",
        "user_muted": "Successfully muted **{}** for **{}**",
        "unable_to_unban": "Unable to unban **{}**",
        "bot_error": "Bot Error",
        "unable_to_unmute": "Unable to unmute **{}**",
        "user_unmuted": "**{}** has been successfully unmuted",
        "cannot_warn_self": "You cannot warn yourself!",
        "cannot_warn_bot": "You cannot warn a bot!",
        "cannot_warn_administrator": "You cannot warn an administrator!",
        "no_permission_warn": "You do not have permission to warn **{}**!",
        "warning": "Warning",
        "warning_lower": "warning",
        "warnings_lower": "warnings",
        "warning_count": "You now have {0} {1} in {2}",
        "user_warned": "Successfully warned **{}** (**{}**)",
        "unable_to_warn": "Unable to warn **{}**",
        "warnings_reset": "**{}**'s warnings have been successfully reset",
        "not_specified": "Not specified",
        "generate_number_limit": "You have generated **5 numbers** already. Please re-run the command to continue.",
        "expression": "Expression",
        "result": "Result",
        "unknown_answer": "Unknown Answer",
        "second": "second",
        "seconds": "seconds",
        "minute": "minute",
        "minutes": "minutes",
        "hour": "hour",
        "hours": "hours",
        "day": "day",
        "days": "days",
        "month": "month",
        "months": "months",
        "year": "year",
        "years": "years",
        "suggestion_sent": "Your suggestion has been successfully sent",
        "sending_suggestion": "Sending your suggestion...",
        "not_bot_owner": "You are not the owner of Doge Utilities!",
        "infinity": "infinity",
        "no_negative_numbers": "No negative numbers please!",
        "duration_too_long": "The specified duration is too long!",
        "current_language_description": "Your preferred language is set to **{}**",
        "border_size_too_big": "The border size must not exceed 32!",
        "qr_code": "QR Code",
        "qr_create_failed": "Unable to create a QR code",
        "correct_answer": "Correct answer!",
        "wrong_answer": "Wrong answer... The correct answer was **{}**.",
        "unable_to_clear": "Unable to clear messages",
        "max_clear_messages": "You can only clear up to **1000 messages**!",
        "cleared": "Successfully deleted **{} {}**",
        "cleared_from": "Successfully deleted **{} {}** from **{}**",
        "cleared_contains": 'Successfully deleted **{} {}** that contained **"{}"**',
        "cleared_from_contains": 'Successfully deleted **{} {}** from **{}** that contained **"{}"**',
        "message_lower": "message",
        "messages_lower": "messages",
        "bot_error_report": "Doge Utilities error report",
        "joined_game": "Successfully joined the game!",
        "already_joined": "You have already joined the game!",
        "player_one": "Player 1",
        "player_two": "Player 2",
        "game_starts_in_three": "The game starts in **3 seconds**!",
        "join_tictactoe": "Click to join the TicTacToe game",
        "afk_removed": "Your AFK status has been removed!",
        "afk_set": "Your AFK message has been set to **\"{}\"**",
        "currently_afk": "**{}** is currently AFK ({}): **{}**",
        "already_afk": "You are already AFK!",
        "mentioned_user": "The user you mentioned",
        "i_am_afk": "I am AFK",
        "text_too_long": "The specified text is too long!",
        "item_limit": "You can only add up to **{} items**!",
        "channel_locked": "{} has been successfully locked",
        "channel_unlocked": "{} has been successfully unlocked",
        "unable_to_lock": "I am unable to lock {}",
        "unable_to_unlock": "I am unable to unlock {}",
        "wrong_turn": "It is not your turn!",
        "not_in_game": "You did not join that game!",
        "bot_status": "Bot Status",
        "minecraft_server": "Minecraft Server",
        "players": "Players",
        "unknown_upper": "Unknown",
        "unable_to_connect": "Unable to connect",
        "nothing_here": "There is nothing here...",
        "custom_embed_generated": "Your custom embed has been successfully generated!",
        "no_permission_manage_role": "You do not have permission to manage this role!",
        "enter_valid_message_id": "Please enter a valid message ID (that exists in this channel)",
        "unable_to_add_emoji": "I am unable to add an emoji to that message!",
        "reaction_role_created": "A new reaction role has been successfully created!",
        "reaction_roles": "Reaction Roles",
        "no_reaction_roles": "There are no reaction roles in this server",
        "currency_list": "Currency List",
        "invite_link": "Invite Link",
        "leave_server": "Leave Server",
        "leave_server_confirm": "Are you sure you want me to leave this server? Please press the button again to confirm.",
        "leaving_server": "Leaving server...",
        "here_is_invite_link": "Here is Doge Utilities' invite link",
        "source_code": "Source Code",
        "developers": "Developers",
        "ideas": "Ideas",
        "translators": "Translators",
        "big_thanks_to": "Big thanks to {}, and a lot more awesome people!",
        "currency_conversion": "Currency Conversion",
        "source_code_here": "You can find my code [here]({})",
        "banned_word": "Please do not use the word **\"{}\"** in this server!",
        "active_issues": "Active Issues",
        "forks": "Forks",
        "stargazers": "Stargazers",
        "watchers": "Watchers",
        "version_upper": "Version",
        "build_upper": "Build",
        "size_upper": "Size",
        "autorole_disabled": "This server's autorole is now **disabled**",
        "autorole_upper": "Autorole",
        "no_autorole": "This server does not have autorole configured",
        "autorole_description": "This server's autorole is {}",
        "autorole_set": "This server's autorole is now set to {}",
        "application_not_found": "The application you specified wasn't found!",
        "suggestion_accepted": "The suggestion you sent ({}) has been **accepted** by **{}**",
        "suggestion_rejected": "The suggestion you sent ({}) has been **rejected** by **{}**",
        "unable_to_accept": "I was unable to accept that suggestion",
        "unable_to_reject": "I was unable to reject that suggestion",
        "accepted_successfully": "That suggestion has been successfully accepted",
        "rejected_successfully": "That suggestion has been successfully rejected",
        "ignored_successfully": "That suggestion has been successfully ignored",
        "has_sent_suggestion": "{} has sent a suggestion",
        "todo_already_added": "That item is already in your to-do list!",
        "todo_not_added": "That item is not in your to-do list!",
        "item_updated": "That item has been successfully updated!",
        "todo_cleared": "Your to-do list has been successfully cleared!",
        "operation_cancelled": "Operation cancelled!",
        "todo_clear_confirm": "Are you sure you want to clear your to-do list?",
        "yes_upper": "Yes",
        "no_upper": "No",
        "repeated_reminders_small": "The minimum duration for repeated reminders is **1 hour**",
        "type": "Type",
        "normal_upper": "Normal",
        "repeated_upper": "Repeated",
        "afk_messages_enabled": "AFK messages have been successfully **enabled**",
        "afk_messages_disabled": "AFK messages have been successfully **disabled**",
        "afk_messages_status": "AFK messages are currently **{}**",
    },
    "zh-cn": {
        "no_permission": "你没有权限使用这个指令!",
        "not_command_sender": "这个指令不是你发的!",
        "vote_message": "谢谢你给我投票!",
        "banned_message": "你已被禁止使用Doge Utilities!",
        "error_message": "很抱歉, Doge Utilities出错了。。。",
        "use_in_server": "请你在服务器里使用Doge Utilities!",
        "no_reminders": "你没有提醒",
        "reminders": "提醒",
        "reminder": "提醒",
        "time": "时间",
        "text": "文字",
        "vote_again": "不要忘记给我投票!",
        "todo_list": "待办事列表",
        "todo_empty": "你的待办事列表是空的",
        "generate_number": "生成数字",
        "number_prompt": "您的随机数字是",
        "cpu_usage": "CPU使用率",
        "ram_usage": "RAM使用率",
        "thread_count": "机器人程序数",
        "joined_guilds": "机器人服务器",
        "active_shards": "机器人碎片",
        "member_count": "用户数",
        "channel_count": "频道数",
        "command_count": "指令数",
        "disnake_version": "Disnake版本",
        "bot_version": "机器人版本",
        "git_commit_hash_upper": "Git提交",
        "last_updated_upper": "更新时间",
        "bot_uptime": "运行时间",
        "latency": "延迟",
        "shard": "碎片",
        "members_lower": "用户",
        "guilds_lower": "服务器",
        "i_choose": "我选择",
        "shard_count": "碎片数",
        "current_shard": "当前碎片",
        "reminder_removed": "那个提醒已被成功移除!",
        "reminder_added": "你会在**{}**后被提醒",
        "support_server": "我的服务器",
        "user_accounts": "用户账号",
        "bot_accounts": "机器人账号",
        "total_members": "全部账号",
        "guild_members": "服务器成员",
        "todo_added": '我成功的把 **"{}"** 加到了你的待办事列表',
        "todo_removed": '我成功的把你待办事列表里的 **"{}"** 移除了',
        "uptime_description": "我已经运行了",
        "current_time": "时间",
        "current_date": "日期",
        "weekday": "星期",
        "time_description": "关于",
        "weekdays": ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期天"],
        "vote_websites": "你可以在这些网站上给我投票",
        "vote_reminder_added": "我成功的给你加了一个**12小时的提醒**!",
        "vote_reminder_exists": "你已经有了一个提醒!",
        "vote_add_reminder": "加一个提醒",
        "vote_messages_enabled": "投票通知已被成功**打开**",
        "vote_messages_disabled": "投票通知已被成功**关闭**",
        "enabled_lower": "打开",
        "disabled_lower": "关闭",
        "vote_messages_status": "投票消息现在属于**{}**状态",
        "language_update": "你的语言已被换成**{}**",
        "language_name": "中文",
        "website_links": "这我是我的网站的链接",
        "website": "网站",
        "dashboard": "控制板",
        "user_kicked": "**{}**已被**成功剔除**",
        "user_banned": "**{}**已被**成功封锁**",
        "unable_to_kick": "我无法剔除**{}**",
        "unable_to_ban": "我无法封锁**{}**",
        "mention_valid_user": "请@一个服务器成员!",
        "user_id": "用户ID",
        "user_tag": "账号",
        "creation_time": "创造时间",
        "public_flags": "属性",
        "bot_user": "机器人用户",
        "system_user": "系统用户",
        "command_cooldown": "指令冷却",
        "command_cooldown_description": "请在**{}**后使用`{}`",
        "invalid_duration": "请输入一个正确的时间!",
        "no_permission_kick": "你没有权限剔除**{}**!",
        "no_permission_ban": "你没有权限封锁**{}**!",
        "unable_to_mute": "我无法禁言**{}**",
        "no_permission_mute": "你没有权限禁言**{}**!",
        "no_permission_unmute": "你没有权限解**{}**的禁言!",
        "user_muted": "我成功禁言了**{}** (**{}**)",
        "unable_to_unban": "我无法解除**{}**的封锁",
        "bot_error": "机器人错误",
        "unable_to_unmute": "我无法解**{}**的禁言",
        "user_unmuted": "**{}**的禁言已被成功解除",
        "cannot_warn_self": "你不能警告你自己!",
        "cannot_warn_bot": "你不能警告一个机器人!",
        "cannot_warn_administrator": "你不能警告一个管理员!",
        "no_permission_warn": "你没有权限警告**{}**!",
        "warning": "警告",
        "warning_lower": "警告",
        "warnings_lower": "警告",
        "warning_count": "你在{2}有{0}个{1}",
        "user_warned": "成功的警告了**{}** (**{}**)",
        "unable_to_warn": "我无法警告**{}**",
        "warnings_reset": "**{}**的警告已被成功清除",
        "not_specified": "无原因",
        "generate_number_limit": "你已经生成了**五个数字**。如果你想继续, 请重新运行指令。",
        "expression": "数学题",
        "result": "结果",
        "unknown_answer": "未知答案",
        "second": "秒",
        "seconds": "秒",
        "minute": "分钟",
        "minutes": "分钟",
        "hour": "小时",
        "hours": "小时",
        "day": "天",
        "days": "天",
        "month": "月",
        "months": "月",
        "year": "年",
        "years": "年",
        "suggestion_sent": "你的建议已被成功发送",
        "sending_suggestion": "正在发送你的建议。。。",
        "not_bot_owner": "你不是Doge Utilities的主人!",
        "infinity": "无数",
        "no_negative_numbers": "请不要输入负数!",
        "duration_too_long": "你提供的时间太长了!",
        "current_language_description": "你的显示语言是**{}**",
        "border_size_too_big": "边框大小不能超过32!",
        "qr_code": "QR码",
        "qr_create_failed": "我无法生成二维码",
        "correct_answer": "你答对了!",
        "wrong_answer": "你答错了。。。真确答案是**{}**。",
        "unable_to_clear": "我无法清除消息",
        "max_clear_messages": "你最多只能清除**1000个消息**!",
        "cleared": "我成功清除了**{}个{}**",
        "cleared_from": "我成功清除了来自**{2}**的**{0}个{1}**",
        "cleared_contains": '我成功清除了含有**"{2}"**的**{0}个{1}**',
        "cleared_from_contains": '我成功清除了来自**{2}**含有**"{3}"**的**{0}个{1}**',
        "message_lower": "消息",
        "messages_lower": "消息",
        "bot_error_report": "Doge Utilities错误报告",
        "joined_game": "成功加入了游戏!",
        "already_joined": "你已经加入了游戏!",
        "player_one": "玩家1",
        "player_two": "玩家2",
        "game_starts_in_three": "游戏会在**3秒**后开始!",
        "join_tictactoe": "点击按钮加入TicTacToe游戏",
        "afk_removed": "你的AFK已被移除!",
        "afk_set": "你的AFK消息已被设成**\"{}\"**",
        "currently_afk": "**{}**现在是AFK ({}): **{}**",
        "already_afk": "你已经是AFK!",
        "mentioned_user": "你@的用户",
        "i_am_afk": "我不在",
        "text_too_long": "你提供的字太长了!",
        "item_limit": "你只能加**{}个**物品!",
        "channel_locked": "{} 已被成功锁定",
        "channel_unlocked": "{} 已被成功解锁",
        "unable_to_lock": "我无法锁定 {}",
        "unable_to_unlock": "我无法解锁 {}",
        "wrong_turn": "这不是你玩的时候!",
        "not_in_game": "你没有加入那个游戏!",
        "bot_status": "机器人状态",
        "minecraft_server": "我的世界服务器",
        "players": "玩家",
        "unknown_upper": "未知",
        "unable_to_connect": "无法连接",
        "nothing_here": "这里没东西。。。",
        "custom_embed_generated": "你的嵌入已被成功生成!",
        "no_permission_manage_role": "你没有权限管理这个身份组!",
        "enter_valid_message_id": "请输入一个在这个频道里存在的消息ID!",
        "unable_to_add_emoji": "我无法在那个消息上加emoji!",
        "reaction_role_created": "我成功的创造了一个新的反应身分组!",
        "reaction_roles": "反应身分组",
        "no_reaction_roles": "这个服务器没有反应身分组",
        "currency_list": "货币列表",
        "invite_link": "邀请链接",
        "leave_server": "退出服务器",
        "leave_server_confirm": "你确定你要让我退出这个服务器吗? 如果你真的要让我退出, 请再按一次按钮。",
        "leaving_server": "正在退出服务器。。。",
        "here_is_invite_link": "这是我的邀请链接",
        "source_code": "源代码",
        "developers": "开发者",
        "ideas": "建议",
        "translators": "翻译",
        "big_thanks_to": "很感谢 {}, 和很多其他人!",
        "currency_conversion": "货币转换",
        "source_code_here": "你可以在[这里]({})找到我的源代码",
        "banned_word": "请不要此服务器中使用**\"{}\"**这个词!",
        "active_issues": "问题",
        "forks": "克隆",
        "stargazers": "点赞",
        "watchers": "观看",
        "version_upper": "版本",
        "build_upper": "更新",
        "size_upper": "大小",
        "autorole_disabled": "这个服务器的自动身份组已被成功**关闭**",
        "autorole_upper": "自动身份组",
        "no_autorole": "这个服务器没有设置自动身份组",
        "autorole_description": "这个服务器的自动身份组是 {}",
        "autorole_set": "这个服务器的自动身份组已被设置成 {}",
        "application_not_found": "你提供的机器人不存在!",
        "suggestion_accepted": "您发送的建议 ({}) 被 **{}** 接受了",
        "suggestion_rejected": "您发送的建议 ({}) 被 **{}** 拒绝了",
        "unable_to_accept": "我无法接受那个建议",
        "unable_to_reject": "我无法拒绝那个建议",
        "accepted_successfully": "建议已被成功接受",
        "rejected_successfully": "建议已被成功拒绝",
        "ignored_successfully": "建议已被成功忽略",
        "has_sent_suggestion": "{} 发送了一个建议",
        "todo_already_added": "那个物品已经在您的待办事列表里了!",
        "todo_not_added": "那个物品不在您的待办事列表里!",
        "item_updated": "那个物品已被成功更新!",
        "todo_cleared": "您的待办事列表已被成功清除!",
        "operation_cancelled": "已取消!",
        "todo_clear_confirm": "您确定您要清除你的待办事列表吗?",
        "yes_upper": "是",
        "no_upper": "否",
        "repeated_reminders_small": "重复提醒的最小时间段是**1小时**",
        "type": "类型",
        "normal_upper": "正常",
        "repeated_upper": "重复",
        "afk_messages_enabled": "AFK消息已被成功**开启**",
        "afk_messages_disabled": "AFK消息已被成功**关闭**",
        "afk_messages_status": "AFK消息现在属于**{}**状态",
    },
    "de": {
        "no_permission": "Du hast keine Berechtigung diesen Befehl zu benutzen!",
        "not_command_sender": "Du hast den Befehl nicht benutzt!",
        "vote_message": "Danke dass du Doge Utilities Bewertet hast!",
        "banned_message": "Du bist von Doge Utilities gesperrt",
        "error_message": "Ups! Doge Utilities hatte einen Fehler...",
        "shard": "Shard",
        "latency": "Latenz",
        "time": "Wann",
        "text": "Text",
        "reminder": "Erinnerung",
        "reminders": "Erinnerungen",
        "cpu_usage": "CPU Auslastung",
        "ram_usage": "RAM Auslastung",
        "thread_count": "Anzahl der Threads",
        "joined_guilds": "Servern beigetreten",
        "active_shards": "Aktive Shards",
        "member_count": "Anzahl der Mitglieder",
        "channel_count": "Anzahl der Kanäle",
        "command_count": "Anzahl der Commands",
        "disnake_version": "Disnake Version",
        "bot_version": "Bot Version",
        "bot_uptime": "Bot online seit",
        "i_choose": "Ich wähle",
        "members_lower": "Mitglieder",
        "guilds_lower": "Server",
        "current_shard": "Aktueller Shard",
        "shard_count": "Shards",
        "use_in_server": "Bitte nutze Doge Utilities in einem Server für das bestmögliche Ergebnis!",
        "no_reminders": "Du hast keine aktiven Erinnerungen",
        "vote_again": "Vergiss nicht für mich zu voten!",
        "todo_list": "To-do Liste",
        "todo_empty": "Deine To-do Liste ist leer",
        "generate_number": "Generiere eine Nummer",
        "number_prompt": "Deine generierte Nummer ist",
        "reminder_removed": "Diese Erinnerung wurde erfolgreich entfernt!",
        "reminder_added": "Du wirst erinnert in **{}**",
        "minute": "Minute",
        "minutes": "Minuten",
        "support_server": "Doge Utilities Support Server",
        "user_accounts": "Nutzer Accounts",
        "bot_accounts": "Bot Accounts",
        "total_members": "Alle Mitglieder",
        "guild_members": "Server Mitglieder",
        "todo_added": '**"{}"** wurde erfolgreich zur To-do Liste hinzugefügt',
        "todo_removed": '**"{}"** wurde erfolgreich aus der To-do Liste entfernt',
        "uptime_description": "Doge Utilities ist online seit",
        "current_time": "Uhrzeit",
        "current_date": "Datum",
        "weekday": "Wochentag",
        "time_description": "Informationen für",
        "weekdays": ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
        "vote_websites": "Du kannst für mich auf folgenden Websites voten",
        "vote_reminder_added": "Eine **12 Stunden Erinnerung** wurde erfolgreich hinzugefügt!",
        "vote_reminder_exists": "Es gibt bereits eine Erinnerung!",
        "vote_add_reminder": "Füge eine Erinnerung hinzu",
        "vote_messages_enabled": "Vote Benachrichtigungen wurden erfolgreich **aktiviert**",
        "vote_messages_disabled": "Vote Benachrichtigungen wurden erfolgreich **deaktiviert**",
        "enabled_lower": "aktiviert",
        "disabled_lower": "deaktiviert",
        "vote_messages_status": "Vote Benachrichtigungen sind derzeit **{}**",
        "language_update": "Deine Sprache wurde auf **{}** gesetzt",
        "language_name": "deutsch",
        "website_links": "Hier sind Links für meine Website",
        "website": "Website",
        "dashboard": "Dashboard",
        "user_kicked": "**{}** wurde erfolgreich gekickt",
        "user_banned": "**{}** wurde erfolgreich gebannt",
        "unable_to_kick": "**{}** Kicken nicht möglich",
        "unable_to_ban": "**{}** bannen nicht möglich",
        "mention_valid_user": "Bitte erwähne einen gültigen Nutzer",
        "user_id": "Nutzer ID",
        "user_tag": "Tag",
        "creation_time": "Zeitpunkt der Erstellung",
        "public_flags": "Public Flags",
        "bot_user": "Bot Nutzer",
        "system_user": "System Nutzer",
        "command_cooldown": "Command cool-down",
        "invalid_duration": "Bitte gib einen gültigen Zeitraum an",
        "no_permission_kick": "Du hast keine Berechtigungen um **{}** zu kicken",
        "no_permission_ban": "Du hast keine Berechtigungen **{}** zu bannen",
        "unable_to_mute": "**{}** nuten nicht möglich",
        "no_permission_mute": "Du hast keine Berechtigungen **{}** zu muten",
        "no_permission_unmute": "Du hast keine Berechtigungen **{}** zu unmuten",
        "unable_to_unban": "**{}** bannen nicht möglich",
        "bot_error": "Bot Fehler",
        "unable_to_unmute": "**{}** unmuten nicht möglich",
        "user_unmuted": "**{}** erfolgreich unmuted",
        "cannot_warn_self": "Du kannst dich nicht selbst verwarnen!",
        "cannot_warn_bot": "Du kannst keinen Bot verwarnen!",
        "cannot_warn_administrator": "Du kannst keine Administratoren warnen!",
        "no_permission_warn": "Du hast keine Berechtigungen **{}** zu warnen!",
        "warning": "Warnung",
        "warning_lower": "Warnung",
        "warnings_lower": "Warnungen",
        "warning_count": "Du hast jetzt {0} {1} in {2}",
        "user_warned": "**{}** wurde erfolgreich gewarnt. (**{}**)",
        "unable_to_warn": "**{}** warnen nicht möglich",
        "warnings_reset": "Die Warnungen von **{}** wurden erfolgreich zurückgesetzt",
        "not_specified": "Nicht angegeben",
        "command_cooldown_description": "Bitte warte **{}** befor du den `{}` Befehl wieder benutzen kannst",
        "generate_number_limit": "Du hast bereits 5 Zahlen generiert. Bitte führe den Befehl erneut aus, um weiterzumachen.",
        "expression": "Rechnung",
        "result": "Ergebnis",
        "unknown_answer": "Unbekannte Antwort",
        "second": "Sekunde",
        "seconds": "Sekunden",
        "hour": "Stunde",
        "hours": "Stunden",
        "day": "Tag",
        "days": "Tage",
        "month": "Monat",
        "months": "Monate",
        "year": "Jahr",
        "years": "Jahre",
        "suggestion_sent": "Dein Vorschlag wurde erfolgreich abgesendet",
        "sending_suggestion": "Dein Vorschlag wird abgeschickt...",
        "not_bot_owner": "Du bist nicht der Besitzer von Doge Utilities!",
        "infinity": "Unendlich",
        "no_negative_numbers": "Bitte keine negativen Zahlen!",
        "duration_too_long": "Die angegebene Dauer ist zu lang!",
        "current_language_description": "Deine bevorzugte Sprache wurde zu **{}** geändert",
        "border_size_too_big": "Die länge der Randes darf 32 nicht überschreiten!",
        "qr_code": "QR Code",
        "qr_create_failed": "Erstellen des QR Codes ist nicht möglich",
        "correct_answer": "Richtige Antwort!",
        "wrong_answer": "Falsche Antwort... die richtige Antwort war **{}**",
        "unable_to_clear": "Löschen der Nachrichten nicht möglich",
        "max_clear_messages": "Du kannst maximal **1000 Nachrichten** löschen",
        "cleared": "Erfolgreich **{} {}** gelöscht",
        "cleared_from": "Erfolgreich **{} {}** von **{}** gelöscht",
        "cleared_contains": "Erfolgreich **{} {}** gelöscht, mit dem Inhalt **{}**",
        "cleared_from_contains": "Erfolgreich **{} {}** von **{}** gelöscht, mit dem Inhalt **{}**",
        "message_lower": "Nachricht",
        "messages_lower": "Nachrichten",
        "bot_error_report": "Doge Utilities Error Report",
        "joined_game": "Dem Spiel erfolgreich beigetreten!",
        "already_joined": "Du bist dem Spiel bereits beigetreten!",
        "player_one": "Spieler 1",
        "player_two": "Spieler 2",
        "game_starts_in_three": "Das Spiel startet in **3 Sekunden**!",
        "join_tictactoe": "Klicke, um der TicTacToe Partie beizutreten",
        "afk_removed": "Dein AFK wurde entfernt!",
        "afk_set": "Deine AFK Nachricht wurde auf **\"{}\"** gesetzt",
        "currently_afk": "**{}** ist im Moment AFK ({}): **{}**",
        "already_afk": "Du bist bereits AFK!",
        "mentioned_user": "Der Nutzer, den du erwähnt hast",
        "i_am_afk": "Ich bin AFK",
        "text_too_long": "Der angegebene Text ist zu lang!",
        "item_limit": "Du kannst maximal **{} Elemente** hinzufügen!",
        "channel_locked": "{} wurde erfolgreich gesperrt",
        "channel_unlocked": "{} wurde erfolgreich entsperrt",
        "unable_to_lock": "Ich kann {} nicht sperren",
        "unable_to_unlock": "Ich kann {} nicht entsperren",
        "wrong_turn": "Du bist nicht an der Reihe!",
        "not_in_game": "Du bist diesem Spiel nicht beigetreten!",
        "bot_status": "Bot Status",
        "user_muted": "**{}** wurde erfolgreich für **{}** gemuted",
        "minecraft_server": "Minecraft Server",
        "players": "Spieler",
        "unknown_upper": "Unbekannt",
        "unable_to_connect": "Verbindung fehlgeschlagen",
        "nothing_here": "Es ist nichts hier...",
        "custom_embed_generated": "Deine eigene Embed wurde erfolgreich erstellt!",
        "no_permission_manage_role": "Du hast keine Berechtigungen, diese Rolle zu verwalten!",
        "enter_valid_message_id": "Bitte gib eine gültige Nachrichten ID von einer Nachricht aus diesem Kanal ein",
        "unable_to_add_emoji": "Ich kann keine Emoji zu dieser Nachricht hinzufügen!",
        "reaction_role_created": "Eine neue Reaction Rolle wurde erfolgreich erstellt!",
        "reaction_roles": "Reaction Rollen",
        "no_reaction_roles": "Es gibt keine Reaction Rollen auf diesem Server",
        "currency_list": "Währungsliste",
        "invite_link": "Einladungslink",
        "leave_server": "Server verlassen",
        "leave_server_confirm": "Sicher, dass ich diesen Server verlassen soll? Bestätige bitte erneut einem weiteren Klick.",
        "leaving_server": "Verlasse Server...",
        "here_is_invite_link": "Hier ist Doge Utilities' Einladungslink!",
        "source_code": "Quellcode",
        "developers": "Entwickler",
        "ideas": "Ideen",
        "translators": "Übersetzer",
        "big_thanks_to": "Großes Danke an {}, und noch viel mehr großartige Personen!",
        "currency_conversion": "Währungsunwandlung",
        "source_code_here": "Du kannst meinen Programmcode [hier]({}) finden",
        "banned_word": "Bitte nutze nicht das Wort **\"{}\"** auf diesem Server!",
        "active_issues": "Aktuelle Probleme",
        "forks": "Kopie",
        "stargazers": "Stargazers",
        "watchers": "Beobachter",
        "version_upper": "Version",
        "build_upper": "Aktualisierung",
        "size_upper": "Größe",
        "autorole_disabled": "Die automatisierten Rollen für diesen Server sind **deaktiviert**",
        "autorole_upper": "Automatisierte Rolle",
        "no_autorole": "Dieser Server hat keine automatisierten Rollen konfiguriert",
        "autorole_description": "Die automatisiere Rolle für diesen Sever ist {}",
        "autorole_set": "Die automatisierte Rolle dieses Servers wurde auf {} gesetzt",
        "application_not_found": "Deine angegebene Anwendung wurde nicht gefunden",
        "suggestion_accepted": "Dein Vorschlag ({}) wurde von **{}** akzeptiert",
        "suggestion_rejected": "Dein Vorschlag ({}) wurde von **{}** abgelehnt",
        "unable_to_accept": "Ich konnte diesen Vorschlag nicht annehmen",
        "unable_to_reject": "Ich konnte diesen Vorschlag nicht ablehnen",
        "accepted_successfully": "Dieser Vorschlag wurde erfolgreich akzeptiert",
        "rejected_successfully": "Dieser Vorschlag wurde erfolgreich abgelehnt",
        "ignored_successfully": "Dieser Vorschlag wurde ignoriert",
        "has_sent_suggestion": "{} hat etwas vorgeschlagen",
    },
    "ru": {
        "no_permission": "У вас нет разрешений на использование этой команды!",
        "not_command_sender": "Вы не являетесь отправителем данной команды!",
        "vote_message": "Спасибо за то, что вы проголосовали за меня!",
        "banned_message": "Вам запретили использовать Doge Utilities!",
        "error_message": "Упс... Doge Utilities столкнулся с ошибкой...",
        "use_in_server": "Пожалуйста, используйте Doge Utilities на сервере для лучшего опыта!",
        "no_reminders": "У вас нет активных напоминаний",
        "reminders": "Напоминания",
        "time": "Время",
        "text": "Текст",
        "todo_list": "Список дел",
        "support_server": "Сервер поддержки Doge Utilities",
        "vote_again": "Не забывай голосовать за меня!",
        "todo_empty": "Ваш список дел пустой",
        "generate_number": "Сгенерировать число",
        "number_prompt": "Ваше случайное число",
        "cpu_usage": "Использование CPU",
        "ram_usage": "Использование RAM",
        "thread_count": "Количество потоков",
        "active_shards": "Активные шарды",
        "member_count": "Количество участников",
        "channel_count": "Количество каналов",
        "command_count": "Количество команд",
        "disnake_version": "Версия Disnake",
        "bot_version": "Версия бота",
        "bot_uptime": "Время работы",
        "shard": "Шард",
        "members_lower": "участники",
        "guilds_lower": "гильдии",
        "i_choose": "Я выбрал",
        "shard_count": "Количество шардов",
        "current_shard": "Текущий шард",
        "reminder_removed": "Это напоминание было успешно удалено!",
        "reminder_added": "Вам напомнят в **{}**",
        "minute": "минута",
        "minutes": "минуты",
        "latency": "Задержка",
        "joined_guilds": "Гильдий",
        "uptime_description": "Doge Utilities работает",
        "reminder": "Напоминание",
        "user_accounts": "Учетные записи пользователей",
        "bot_accounts": "Аккаунты ботов",
        "total_members": "Всего участников",
        "guild_members": "Участники гильдии",
        "todo_added": '**"{}"** был успешно добавлен к вашему списку дел',
        "todo_removed": '**"{}"** {} был успешно удален с вашего списка дел',
        "current_time": "Время",
        "current_date": "Дата",
        "weekday": "День недели",
        "time_description": "Информация для",
        "weekdays": ["Понедельник", "вторник", "среда", "четверг", "пятница", "суббота", "воскресенье"],
        "vote_websites": "Вы можете проголосовать за меня на этих вебсайтах",
        "vote_reminder_added": "**12 часовое напоминание** было успешно добавлено!",
        "vote_reminder_exists": "Напоминание уже существует!",
        "vote_add_reminder": "Добавить напоминание",
        "vote_messages_enabled": "Сообщения голосования успешно **включены**",
        "vote_messages_disabled": "Сообщения голосования успешно **отключены**",
        "enabled_lower": "включены",
        "disabled_lower": "отключены",
        "vote_messages_status": "Сообщения о голосовании в настоящее время **{}**",
        "language_update": "Ваш основной язык установлен на **{}**",
        "language_name": "русский",
        "website_links": "Вот ссылка на мой вебсайт",
        "website": "Вебсайт",
        "dashboard": "Панель управления",
        "user_kicked": "**{}** успешно кикнут",
        "user_banned": "**{}** успешно забанен",
        "unable_to_kick": "Невозможно кикнуть **{}**",
        "unable_to_ban": "Невозможно забанить **{}**",
        "mention_valid_user": "Пожалуйста, укажите правильного пользователь",
        "user_id": "Айди",
        "user_tag": "Тег",
        "creation_time": "Дата создания",
        "public_flags": "Публичные флаги",
        "bot_user": "Боты",
        "system_user": "Системный пользователь",
        "command_cooldown": "Задержка команды",
        "invalid_duration": "Пожалуйста, укажите правильную задержу",
        "no_permission_kick": "Вы не имеете права кикнуть **{}**",
        "no_permission_ban": "Вы не имеете права забанить **{}**",
        "unable_to_mute": "Невозможно замьютить **{}**",
        "no_permission_mute": "Вы не имеете право замьютить **{}**",
        "no_permission_unmute": "Вы не имеете права замьютить **{}**",
        "unable_to_unban": "Невозможно разбанить **{}**",
        "bot_error": "Ошибка бота",
        "unable_to_unmute": "Невозможно размьютить **{}**",
        "user_unmuted": "**{}** успешно размьючен",
        "cannot_warn_self": "Вы не можете дать предупреждение самому себе!",
        "cannot_warn_bot": "Вы не можете дать предупреждение боту!",
        "cannot_warn_administrator": "Вы не можете дать предупреждение администатору!",
        "no_permission_warn": "Вы не имеете права дать предупреждение **{}**!",
        "warning": "Предупреждение",
        "warning_lower": "предупреждение",
        "warnings_lower": "предупреждения",
        "warning_count": "Теперь у вас есть {0} {1} в {2}",
        "user_warned": "**{}** успешно предупреждён (**{}**)",
        "unable_to_warn": "Невозможно дать предупреждение **{}**",
        "warnings_reset": "Предупреждения **{}** было успешно сняты",
        "not_specified": "Не указано",
    },
    "sk": {
        "no_permission": "Nemáš oprávnenie na použitie tohto príkazu!",
        "not_command_sender": "Nie si odosielateľom toho príkazu!",
        "vote_message": "Ďakujeme Ti za hlasovanie za Doge Utilities!",
        "banned_message": "Máš zakázané používať Doge Utilities!",
        "error_message": "Ups! Doge Utilities narazil na chybu...",
        "use_in_server": "Prosím, používaj Doge Utilities na serveri pre najlepší dojem!",
        "no_reminders": "Nemáš žiadne aktívne pripomienky",
        "reminders": "Pripomienky",
        "reminder": "Pripomienka",
        "time": "Čas",
        "text": "Text",
        "vote_again": "Nezabudni za mňa zahlasovať!",
        "todo_list": "Zoznam úloh",
        "todo_empty": "Tvoj zoznam úloh je prázdny",
        "generate_number": "Vygeneruj Číslo",
        "number_prompt": "Tvoje náhodné číslo je",
        "cpu_usage": "Využitie procesora",
        "ram_usage": "Využitie pamäte RAM",
        "thread_count": "Počet vlákien",
        "joined_guilds": "Pripojených serverov",
        "active_shards": "Aktívnych inštancií",
        "member_count": "Počet používateľov",
        "channel_count": "Počet kanálov",
        "command_count": "Počet príkazov",
        "disnake_version": "Verzia Disnake",
        "bot_version": "Verzia Bot-a",
        "bot_uptime": "Čas prevádzky",
        "latency": "Odozva",
        "shard": "inštancia",
        "members_lower": "používateľov",
        "guilds_lower": "serverov",
        "i_choose": "Ja si vyberám",
        "shard_count": "Počet inštancií",
        "current_shard": "Aktuálna inštancia",
        "reminder_removed": "Daná pripomienka bola úspešne odstránená!",
        "reminder_added": "Pripomenutie bude uskutočnené za **{}**",
        "minute": "minúta",
        "minutes": "minúty",
        "support_server": "Server podpory Doge Utilities",
        "user_accounts": "Účty používateľov",
        "bot_accounts": "Účty bot-ov",
        "total_members": "Celkovo používateľov",
        "guild_members": "Používatelia servera",
        "todo_added": "Úspešne pridané **{}** do tvojho zoznamu úloh",
        "todo_removed": "Z tvojho zoznamu úloh bolo úspešne odstránené **{}**",
        "uptime_description": "Doge Utilities je v prevádzke",
        "current_time": "Čas",
        "current_date": "Dátum",
        "weekday": "Pracovný deň",
        "time_description": "Informácia pre",
        "weekdays": ['Pondelok', 'Utorok', 'Streda', 'Štvrtok', 'Piatok', 'Sobota', 'Nedeľa'],
        "vote_websites": "Hlasovať za mňa môžeš na týchto stránkach",
        "vote_reminder_added": "12 hodinová pripomienka bola úspešne pridaná!",
        "vote_reminder_exists": "Pripomienka už existuje!",
        "vote_add_reminder": "Pridať pripomienku",
        "vote_messages_enabled": "Správy na hlasovanie boli úspešne zapnuté",
        "vote_messages_disabled": "Správy na hlasovanie boli úspešne vypnuté",
        "enabled_lower": "zapnuté",
        "disabled_lower": "vypnuté",
        "vote_messages_status": "Správy na hlasovanie sú momentálne **{}**",
        "language_update": "Tvoj preferovaný jazyk bol nastavený na **{}**",
        "language_name": "Angličtina",
        "website_links": "Tu sú odkazy na moje web stránky",
        "website": "Webová stránka",
        "dashboard": "Nástenka",
        "user_kicked": "**{}** bol úspešne vyhodený",
        "user_banned": "**{}** bol úspešne zablokovaný",
        "unable_to_kick": "Nie som schopný vyhodiť **{}**",
        "unable_to_ban": "Nie som schopný zablokovať **{}**",
        "mention_valid_user": "Prosím, označ platného používateľa!",
        "user_id": "Používateľské ID",
        "user_tag": "Označenie",
        "creation_time": "Čas vytvorenia",
        "public_flags": "Verejné vlajky",
        "bot_user": "Účet bot-a",
        "system_user": "Systémový používateľ",
        "command_cooldown": "Presiahnutá rýchlosť posielania príkazov",
        "invalid_duration": "Prosím zadaj platnú dĺžku!",
        "no_permission_kick": "Nemáš oprávnenie vyhodiť **{}**!",
        "no_permission_ban": "Nemáš oprávnenie zablokovať **{}**!",
        "unable_to_mute": "Nie som schopný stlmiť **{}**",
        "no_permission_mute": "Nemáš oprávnenie stlmiť **{}**!",
        "no_permission_unmute": "Nemáš oprávnenie zrušiť stlmenie **{}**!",
        "unable_to_unban": "Nie som schopný odblokovať **{}**",
        "bot_error": "Chyba bot-a",
        "unable_to_unmute": "Nie som schopný zrušiť stlmenie **{}**",
        "user_unmuted": "Úspešne zrušené stlmenie používateľa **{}**",
        "cannot_warn_self": "Nemôžeš varovať sám seba!",
        "cannot_warn_bot": "Nemôžeš varovať bot-a!",
        "cannot_warn_administrator": "Nemôžeš varovať administrátora!",
        "no_permission_warn": "Nemáš oprávnenie varovať **{}**!",
        "warning": "Varovanie",
        "warning_lower": "varovanie",
        "warnings_lower": "varovania",
        "warning_count": "Teraz máš {0} {1} v {2}",
        "user_warned": "Používateľ **{}** bol úspešne varovaný za (**{}**)",
        "unable_to_warn": "Nie som schopný varovať **{}**",
        "warnings_reset": "Varovania používateľa **{}** boli resetované",
        "not_specified": "Nešpecifikované",
        "command_cooldown_description": "Prosím počkaj **{}** pred opakovaným použitím príkazu `{}`",
        "generate_number_limit": "Už si vygeneroval 5 náhodných čísel. Ak chceš generovať ďalšie náhodné čísla, spusti znovu príkaz.",
        "expression": "Výraz",
        "result": "Výsledok",
        "unknown_answer": "Neznáma odpoveď",
        "second": "sekunda",
        "seconds": "sekundy",
        "hour": "hodina",
        "hours": "hodiny",
        "day": "deň",
        "days": "dni",
        "month": "mesiac",
        "months": "mesiace",
        "year": "rok",
        "years": "roky",
        "suggestion_sent": "Tvoj nápad bol úspešne zaznamenaný",
        "sending_suggestion": "Odosielam tvoj nápad...",
        "not_bot_owner": "Nie si majiteľom Doge Utilities!",
        "infinity": "nekonečno",
        "no_negative_numbers": "Nepoužívajte prosím záporné čísla!",
        "duration_too_long": "Daná časová dĺžka je príliš dlhá!",
        "current_language_description": "Tvoj preferovaný jazyk bol nastavený na **{}**",
        "border_size_too_big": "Veľkosť hranice nesmie presiahnuť 32!",
        "qr_code": "QR kód",
        "qr_create_failed": "Nebolo možné vytvoriť QR kód",
        "correct_answer": "Správna odpoveď!",
        "wrong_answer": "Nesprávne... Správna odpoveď bola **{}**.",
        "unable_to_clear": "Nebolo možné vymazať správy",
        "max_clear_messages": "Môžeš vymazať maximálne 1000 správ!",
        "cleared": "Úspešne vymazaných **{} {}**",
        "cleared_from": "Úspešne vymazaných **{} {}** z **{}**",
        "cleared_contains": "Úspešne vymazaných **{} {}**, ktoré obsahovali **{}**",
        "cleared_from_contains": "Úspešne vymazaných **{} {}** od **{}**, ktoré obsahovali **{}**",
        "message_lower": "správa",
        "messages_lower": "správy",
        "bot_error_report": "Chybové hlásenie Doge Utilities",
        "joined_game": "Úspešné pripojenie k hre!",
        "already_joined": "Už si pripojený k hre!",
        "player_one": "Hráč 1",
        "player_two": "Hráč 2",
        "game_starts_in_three": "Hra začína za 3 sekundy!",
        "join_tictactoe": "Klikni pre pripojenie ku hre piškôriek",
        "afk_removed": "Tvoj AFK bol odstránený!",
        "afk_set": "Tvoja AFK správa bola nastavená na **\"{}\"**",
        "currently_afk": "**{}** je momentálne AFK ({}): **{}**",
        "already_afk": "Už si AFK!",
        "mentioned_user": "Používateľ, ktorého si spomenul/a",
        "i_am_afk": "Som AFK",
        "text_too_long": "Daný text je príliš dlhý!",
        "item_limit": "Môžeš pridať maximálne **{}** vecí!",
        "channel_locked": "{} bol úspešne uzamknutý",
        "channel_unlocked": "{} bol úspešne odomknutý",
        "unable_to_lock": "Nie som schopný zamknúť {}",
        "unable_to_unlock": "Nie sok schopný odomknúť {}",
    },
    "es": {
        "banned_message": "¡Estás baneado del uso de Doge Utilities!",
        "error_message": "¡Oops! Doge Utilities se ha encontrado un error...",
        "use_in_server": "¡Por favor, usa Doge Utilities en un servidor para una mejor experiencia!",
        "no_reminders": "No tienes recordatorios activos",
        "reminders": "Recordatorios",
        "reminder": "Recordatorio",
        "time": "Tiempo",
        "text": "Texto",
        "vote_again": "¡No olvides votar por mi!",
        "todo_list": "Lista de tareas",
        "todo_empty": "Tu lista de tareas está vacía",
        "generate_number": "Generar Número",
        "number_prompt": "Tu número aleatorio es",
        "cpu_usage": "Uso de CPU",
        "ram_usage": "Uso de RAM",
        "thread_count": "Numero de Hilos",
        "joined_guilds": "Servidores Unidos",
        "active_shards": "Fragmentos Activos",
        "member_count": "Cantidad de Mienbros",
        "channel_count": "Cantidad de Canales",
        "command_count": "Cantidad de Comandos",
        "disnake_version": "Versión de Disnake",
        "bot_version": "Versión del Bot",
        "git_commit_hash_upper": "Hash de Git Commit",
        "last_updated_upper": "Ultima Actualización",
        "bot_uptime": "Tiempo de Actividad del Bot",
        "latency": "Latencia",
        "shard": "Fragmento",
        "members_lower": "miembros",
        "guilds_lower": "servidores",
        "i_choose": "Yo eligo",
        "shard_count": "Cantidad de Fragmentos",
        "current_shard": "Fragmento Actual",
        "reminder_removed": "¡El recordatorio ha sido eliminado correctamente!",
        "reminder_added": "Serás recordado en {}",
        "support_server": "Servidor de soporte de Doge Utilities",
        "user_accounts": "Cuentas de usuarios",
        "bot_accounts": "Cuentas de bots",
        "total_members": "Miembros totales",
        "guild_members": "Miembros del Servidor",
        "todo_added": "Añadidos **\"{}\"** elementos correctamente a la lista de tareas",
        "todo_removed": "Eliminados **\"{}\"** elementos correctamente a la lista de tareas",
        "uptime_description": "Doge Utilities ha estado corriendo por",
        "current_time": "Tiempo",
        "current_date": "Fecha",
        "weekday": "Dia de la semana",
        "time_description": "Información para",
        "weekdays": ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
        "vote_websites": "Puedes votar por mi en estas páginas web",
        "vote_reminder_added": "¡Se ha añadido un recordatorio de 12 horas correctamente!",
        "vote_reminder_exists": "¡Un recordatorio ya existe!",
        "vote_add_reminder": "Añadir un recordatorio",
        "vote_messages_enabled": "Mensajes de votación se activado correctamente",
        "vote_messages_disabled": "Mensajes de votación se desactivado correctamente",
        "enabled_lower": "activado",
        "disabled_lower": "desactivado",
        "vote_messages_status": "Los mensajes de votación son {} en este momento",
        "language_update": "Tu lenguaje preferido se ha establecido a {}",
        "language_name": "Inglés",
        "website_links": "Aquí están los enlaces a mi página web",
        "website": "Página Web",
        "dashboard": "Panel",
        "user_kicked": "{} ha sido expulsado correctamente",
        "user_banned": "{} ha sido baneado correctamente",
        "unable_to_kick": "No se ha podido expulsar a {}",
        "unable_to_ban": "No se ha podido banear a {}",
        "mention_valid_user": "¡Por favor, menciona a un usuario válido!",
        "user_id": "ID de Usuario",
        "user_tag": "Etiqueta",
        "creation_time": "Tiempo de la Creación",
        "public_flags": "Banderas Públicas",
        "bot_user": "Usuario Bot",
        "system_user": "Usuario del Sistema",
        "command_cooldown": "Enfriamiento de Comandos",
        "command_cooldown_description": "Por favor, espera {} antes de usar el comando {} otra vez",
        "invalid_duration": "¡Por favor, introduce una duración válida!",
        "no_permission_kick": "¡No tienes permisos para expulsar a {}!",
        "no_permission_ban": "¡No tienes permisos para banear a {}!",
        "unable_to_mute": "No se ha podido silenciar a {}",
        "no_permission_mute": "'No tienes permisos para silenciar a {}!",
        "no_permission_unmute": "¡No tienes permisos para de-silenciar a {}!",
        "user_muted": "Correctamente silenciado a {} por {}",
        "unable_to_unban": "No se ha podido desbanear a {}",
        "bot_error": "Error de Bot",
        "unable_to_unmute": "No se ha podido de-silenciar a {}",
        "user_unmuted": "{} ha sido de-silenciado correctamente",
        "cannot_warn_self": "¡No puedes advertirte a ti mismo!",
        "cannot_warn_bot": "¡No puedes advertir a un bot!",
        "cannot_warn_administrator": "¡No puedes advertir a un administrador!",
        "no_permission_warn": "¡No tienes permisos para advertir a {}!",
        "warning": "Advertencia",
        "warning_lower": "advertencia",
        "warnings_lower": "advertencias",
        "warning_count": "Ahora tienes {0} {1} en {2}",
        "user_warned": "Advertido correctamente a {} ({})",
        "unable_to_warn": "No se ha podido advertir a {}",
        "warnings_reset": "{} advertencias se han reiniciado correctamente",
        "not_specified": "Sin especificar",
        "generate_number_limit": "Ya has generado 5 números. Por favor, vuelve a ejecutar el comando para continuar.",
        "expression": "Expresión",
        "result": "Resultado",
        "unknown_answer": "Respuesta Desconocida",
        "second": "segundo",
        "seconds": "segundos",
        "minute": "minuto",
        "minutes": "minutos",
        "hour": "hora",
        "hours": "horas",
        "day": "día",
        "days": "dias",
        "month": "mes",
        "months": "meses",
        "year": "año",
        "years": "años",
        "suggestion_sent": "Tu sugerencia se ha enviado correctamente",
        "sending_suggestion": "Enviando sugerencia...",
        "not_bot_owner": "¡No eres el dueño de Doge Utilities!",
        "infinity": "infinito",
        "no_negative_numbers": "¡No uses números negativos por favor!",
        "duration_too_long": "¡La duración especificada es muy larga!",
        "current_language_description": "Tu lenguaje preferido es {}",
        "border_size_too_big": "¡El tamaño del borde no debe exceder 32!",
        "qr_code": "Código QR",
        "qr_create_failed": "No se ha podido crear un código QR",
        "correct_answer": "¡Respuesta correcta!",
        "wrong_answer": "Respuesta incorrecta... La respuesta correcta era {}.",
        "unable_to_clear": "No se han podido eliminar los mensajes",
        "max_clear_messages": "¡Solo puedes eliminar hasta 1000 mensajes!",
        "cleared": "Correctamente eliminado {} {}",
        "cleared_from": "Correctamente eliminado {} {} de {}",
        "cleared_contains": "Correctamente eliminado {} {} que contenían {}",
        "cleared_from_contains": "Correctamente eliminado {} {} de {} que contenían {}",
        "message_lower": "mensaje",
        "messages_lower": "mensajes",
        "bot_error_report": "Reporte de error de Doge Utilities",
        "joined_game": "¡Correctamente unido al juego!",
        "already_joined": "¡Ya te has unido a este juego!",
        "player_one": "Jugador 1",
        "player_two": "Jugador 2",
        "game_starts_in_three": "¡El juego empieza en 3 segundos!",
        "join_tictactoe": "Haz click para unirte al 3 en raya",
        "afk_removed": "¡Tu estado AFK se ha eliminado!",
        "afk_set": "¡Tu estado AFK se ha establecido a {}!",
        "currently_afk": "{} está ahora AFK ({}): {}",
        "already_afk": "¡Ya estás AFK!",
        "mentioned_user": "El usuario que has mencionado",
        "i_am_afk": "Estoy AFK",
        "text_too_long": "¡El texto especificado es muy largo!",
        "item_limit": "¡Solo puedes añadir hasta {} elementos!",
        "channel_locked": "{} ha sido bloqueado correctamente",
        "channel_unlocked": "{} ha sido desbloqueado correctamente",
        "unable_to_lock": "No puedo bloquear {}",
        "unable_to_unlock": "No puedo desbloquear {}",
        "wrong_turn": "¡No es tu turno!",
        "not_in_game": "¡No te has unido a ese juego!",
        "bot_status": "Estado del Bot",
        "minecraft_server": "Servidor de Minecraft",
        "players": "Jugadores",
        "unknown_upper": "Desconocido",
        "unable_to_connect": "No se ha podido conectar",
        "nothing_here": "No hay nada aqui...",
        "custom_embed_generated": "¡Tu mensaje embed ha sido generado correctamente!",
        "no_permission_manage_role": "¡No tienes permiso para manejar este rol!",
        "enter_valid_message_id": "Por favor, introduce un ID de mensaje válido (que exista en este canal)",
        "unable_to_add_emoji": "¡No puedo añadir un emoji a ese mensaje!",
        "reaction_role_created": "¡Una nueva reacción de rol se ha creado correctamente!",
        "reaction_roles": "Reacciones de Rol",
        "no_reaction_roles": "No hay reacciones de rol en este servidor",
        "currency_list": "Lista de Divisas",
        "invite_link": "Enlace de Invitación",
        "leave_server": "Abandonar Servidor",
        "leave_server_confirm": "¿Estás seguro que quieres que abandone este servidor? Por favor, presiona el botón otra vez para confirmar.",
        "leaving_server": "Abandonando servidor...",
        "here_is_invite_link": "Aquí está el enlace de invitación de Doge Utilities",
        "source_code": "Código Fuente",
        "developers": "Desarrolladores",
        "ideas": "Ideas",
        "translators": "Traductores",
        "big_thanks_to": "¡Muchas gracias a {} y a mucha más gente asombrosa!",
        "currency_conversion": "Conversión de Divisa",
        "source_code_here": "Puedes encontrar mi código [aquí]({})",
        "banned_word": "¡Por favor, no uses la palabra **\"{}\"** en este servidor!",
        "active_issues": "Asuntos Activos",
        "forks": "Bifurcaciones",
        "stargazers": "Observadores de Estrellas",
        "watchers": "Observadores",
        "version_upper": "Versión",
        "build_upper": "Construcción",
        "size_upper": "Tamaño",
        "autorole_disabled": "Los autoroles de este servidor se han **desactivado**",
        "autorole_upper": "Autorol",
        "no_autorole": "Este servidor no tiene autoroles configurados",
        "autorole_description": "El autorol de este servidor es {}",
        "autorole_set": "El autorol de este servidor es ahora {}",
        "application_not_found": "¡La aplicación que has especificado no se ha encontrado!",
        "suggestion_accepted": "La sugerencia que has enviado ({}) se ha **aceptado** por **{}**",
        "suggestion_rejected": "La sugerencia que has enviado ({}) se ha **rechazado** por **{}**",
        "unable_to_accept": "No he podido aceptar esa sugerencia",
        "unable_to_reject": "No he podido rechazar esa sugerencia",
        "accepted_successfully": "Esa sugerencia ha sido aceptada correctamente",
        "rejected_successfully": "La sugerencua ha sido rechazada correctamente",
        "ignored_successfully": "La sugerencia ha sido ignorada correctamente",
        "has_sent_suggestion": "{} ha enviado una sugerencia",
        "todo_already_added": "¡Ese elemento ya está en tu lista de tareas!",
        "todo_not_added": "¡Ese elemento no está en tu lista de tareas!",
        "item_updated": "¡Ese elemento se ha actualizado correctamente!",
        "todo_cleared": "¡Tu lista de tareas se ha limpiado correctamente!",
        "operation_cancelled": "¡Operación cancelada!",
        "todo_clear_confirm": "¿Estás seguro de que quieres limpiar tu lista de tareas?",
        "yes_upper": "Sí",
        "no_upper": "No",
        "repeated_reminders_small": "La duración mínima para recordatorios repetitivos es **1 hora**",
        "type": "Escribe",
        "normal_upper": "Normal",
        "repeated_upper": "Repetido",
        "afk_messages_enabled": "Mensajes AFK han sido **activados** correctamente",
        "afk_messages_disabled": "Mensajes AFK han sido **desactivados** correctamente",
        "afk_messages_status": "Mensajes AFK están {} actualmente",
    },
}
data["zh-tw"] = data["zh-cn"]


def get(language, key):
    language = language.lower()
    key = key.lower()
    if language not in data.keys():
        language = "en"
    language_data = data[language]
    if key not in language_data:
        language_data = data["en"]
        if key not in language_data:
            return key
        else:
            return language_data[key]
    else:
        return language_data[key]
